# Generated by Django 4.2.6 on 2023-11-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_authen_delete_authen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='authen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.authen'),
        ),
    ]
