# Generated by Django 4.2.6 on 2023-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authen_alter_post_authen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authen',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
